### ISSUE TITLE
Ctrl-E doesn't work for me

### ISSUE THREAD

**Issue by vmedea** [davidbrochart/nbterm#14]
I really like the idea of this!

However I'm having trouble getting nbterm to execute the contents of cells. I can press enter, enter something in the cell, like `print(100)` then press ESC to go back to command mode.

But when I then push Ctrl-E or Ctrl-R, nothing happens. No error message, nothing. Other key bindings (such as Ctrl-Q to quit) do work. Am I overlooking something?

- Debian testing
- Tilix terminal (based on vte like gnome-terminal). I've checked and Ctrl-E does send '\x05' correctly.
- Python 3.9.2
- nbterm 0.0.7 installed in a venv, using `pip3 install nbterm`

**Comment by davidbrochart** [comment]
Do you have a (Python) kernel installed?
```
$ pip install ipykernel
```

**Comment by vmedea** [comment]
That solved it, thank you!

**Comment by nicoguaro** [comment]
> Do you have a (Python) kernel installed?
> 
> ```
> $ pip install ipykernel
> ```

Wouldn't this be a requirement then?

It also solved the problem for me , BTW.

**Comment by davidbrochart** [comment]
But ipykernel is one kernel implementation for Python, why require this one more than another?

**Comment by nicoguaro** [comment]
> But ipykernel is one kernel implementation for Python, why require this one more than another?

You're right. Maybe a mention of `nbterm` not coming with any kernel is better.

**Comment by davidbrochart** [comment]
Will do, thanks!

**Comment by vmedea** [comment]
Yes, I think adding a message when trying to execute a that there is no kernel available would be helpful.

**Comment by JulesGM** [comment]
Definitely, trying to run without a kernel should raise an error

**Comment by davidbrochart** [comment]
I think we should have a status bar for that, see #5.
