### ISSUE TITLE
Import Error from prompt_toolkit

### ISSUE THREAD

**Issue by oricou** [davidbrochart/nbterm#15]
```
# pip3 install nbterm
...
  Downloading prompt_toolkit-3.0.18-py3-none-any.whl (367 kB)
...

% nbterm
...
File "/usr/local/lib/python3.8/dist-packages/nbterm/notebook.py", line 8, in <module>
  from prompt_toolkit.layout import ScrollablePane
ImportError: cannot import name 'ScrollablePane' from 'prompt_toolkit.layout'  
```
I use Linux Mint 20 and Python 3.8.5.

**Comment by griz1112** [comment]
I'm getting this error trying to build on arm64.

**Comment by davidbrochart** [comment]
That's weird, it works locally with prompt-toolkit 3.0.18. Could you show the result of `pip freeze`?

**Comment by oricou** [comment]
Here it is:

% pip3 freeze
alabaster==0.7.12
alembic==1.4.3
apt-clone==0.2.1
apturl==0.5.2
argon2-cffi==20.1.0
async-generator==1.10
attrs==20.3.0
Babel==2.9.0
backcall==0.2.0
beautifulsoup4==4.8.2
bleach==3.2.1
blinker==1.4
Brlapi==0.7.0
cachetools==4.0.0
ccsm==0.9.14.1
certifi==2019.11.28
certipy==0.1.3
cffi==1.14.4
chardet==3.0.4
click==7.1.2
colorama==0.4.3
command-not-found==0.3
commonmark==0.9.1
compizconfig-python==0.9.14.1
configobj==5.0.6
cryptography==3.3.1
cupshelpers==1.0
cycler==0.10.0
dbus-python==1.2.16
decorator==4.4.2
defer==1.0.6
defusedxml==0.6.0
distro==1.4.0
distro-info===0.23ubuntu1
docutils==0.16
entrypoints==0.3
et-xmlfile==1.0.1
fasteners==0.14.1
future==0.18.2
gcalcli==4.2.0
gitdb==4.0.5
GitPython==3.1.14
google-api-python-client==1.7.11
google-auth==1.5.1
google-auth-httplib2==0.0.3
grpcio==1.16.1
httplib2==0.14.0
idna==2.8
ifaddr==0.1.6
imageio==2.9.0
imagesize==1.2.0
inflection==0.5.1
ipykernel==5.4.2
ipyparallel==6.3.0
ipython==7.19.0
ipython-genutils==0.2.0
ipywidgets==7.5.1
jdcal==1.4.1
jedi==0.17.2
Jinja2==2.11.2
jsonschema==3.2.0
jupyter==1.0.0
jupyter-client==6.1.7
jupyter-console==6.2.0
jupyter-core==4.7.0
jupyter-telemetry==0.1.0
jupyterhub==1.3.0
jupyterlab-pygments==0.1.2
jupyterlab-widgets==1.0.0
kernel-driver==0.0.5
keyring==18.0.1
kiwisolver==1.3.1
launchpadlib==1.10.13
lazr.restfulclient==0.14.2
lazr.uri==1.0.3
louis==3.12.0
lxml==4.5.0
Mako==1.1.0
MarkupSafe==1.1.0
matplotlib==3.3.3
mistune==0.8.4
monotonic==1.5
more-itertools==8.6.0
nbclient==0.5.1
nbconvert==6.0.7
nbdime==2.1.0
nbformat==5.0.8
nbterm==0.0.7
nest-asyncio==1.4.3
netifaces==0.10.4
networkx==2.5
nose==1.3.7
notebook==6.1.5
numpy==1.19.4
oauth2client==4.1.2
oauthlib==3.1.0
onboard==1.4.1
openpyxl==3.0.5
packaging==20.3
pamela==1.0.0
pandas==1.1.5
pandocfilters==1.4.3
parsedatetime==2.4
parso==0.7.1
pexpect==4.6.0
pickleshare==0.7.5
Pillow==7.0.0
prometheus-client==0.9.0
prompt-toolkit==3.0.8
protobuf==3.6.1
psutil==5.5.1
ptyprocess==0.6.0
pyasn1==0.4.2
pyasn1-modules==0.2.1
pycairo==1.16.2
pycparser==2.20
pycrypto==2.6.1
pycups==1.9.73
pycurl==7.43.0.2
Pygments==2.7.3
PyGObject==3.36.0
PyICU==2.4.2
PyJWT==1.7.1
pymacaroons==0.13.0
PyNaCl==1.3.0
pyOpenSSL==20.0.1
pyparsing==2.4.6
pyparted==3.11.2
pyrsistent==0.17.3
python-apt==2.0.0+ubuntu0.20.4.4
python-dateutil==2.8.1
python-debian===0.1.36ubuntu1
python-editor==1.0.4
python-json-logger==2.0.1
python-xapp==2.0.1
python-xlib==0.23
pytz==2020.4
PyWavelets==1.1.1
pyxdg==0.26
PyYAML==5.3.1
pyzmq==20.0.0
qtconsole==5.0.1
QtPy==1.9.0
Quandl==3.5.3
reportlab==3.5.34
requests==2.22.0
requests-unixsocket==0.2.0
rich==10.1.0
rsa==4.0
ruamel.yaml==0.16.12
ruamel.yaml.clib==0.2.2
scikit-image==0.18.1
scipy==1.5.4
seaborn==0.11.0
SecretStorage==2.3.1
Send2Trash==1.5.0
setproctitle==1.1.10
simplejson==3.16.0
six==1.14.0
smmap==3.0.5
snowballstemmer==2.0.0
soupsieve==1.9.5
Sphinx==3.3.1
sphinxcontrib-applehelp==1.0.2
sphinxcontrib-devhelp==1.0.2
sphinxcontrib-htmlhelp==1.0.3
sphinxcontrib-jsmath==1.0.1
sphinxcontrib-qthelp==1.0.3
sphinxcontrib-serializinghtml==1.1.4
SQLAlchemy==1.3.22
ssh-import-id==5.10
systemd-python==234
terminado==0.9.1
testpath==0.4.4
tifffile==2021.3.17
tornado==6.1
traitlets==5.0.5
typer==0.3.2
typing-extensions==3.7.4.3
ubuntu-advantage-tools==20.3
ubuntu-drivers-common==0.0.0
ufw==0.36
Unidecode==1.1.1
uritemplate==0.6
urllib3==1.25.8
vobject==0.9.6.1
wadllib==1.3.3
wcwidth==0.2.5
webencodings==0.5.1
widgetsnbextension==3.5.1
xarray==0.16.2
xkit==0.0.0
xlrd==2.0.1
youtube-dl==2021.3.3
zeroconf==0.24.4

**Comment by davidbrochart** [comment]
Thanks, you have `prompt-toolkit==3.0.8`, but 3.0.16 is needed.

**Comment by oricou** [comment]
Argh, an old version in --user space!

**Comment by oricou** [comment]
Thanks
