### ISSUE TITLE
no module named nbterm

### ISSUE THREAD

**Issue by guidov** [davidbrochart/nbterm#2]
Hi, 
after 
python setup.py install 
I get 
——> nbterm
Traceback (most recent call last):
  File "/home/guido/anaconda3/bin/nbterm", line 33, in <module>
    sys.exit(load_entry_point('nbterm==0.0.2', 'console_scripts', 'nbterm')())
  File "/home/guido/anaconda3/bin/nbterm", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/home/guido/anaconda3/lib/python3.8/importlib/metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "/home/guido/anaconda3/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'nbterm'

when am I missing here.
Thanks

**Comment by davidbrochart** [comment]
Try `pip install nbterm`, or from source: `pip install -e .`

**Comment by guidov** [comment]
I did a pip uninstall nbterm 
then (on two different computers)

——> pip install nbterm
Collecting nbterm
  Downloading nbterm-0.0.2-py3-none-any.whl (6.4 kB)
Requirement already satisfied: prompt-toolkit>=3 in ./anaconda3/lib/python3.8/site-packages (from nbterm) (3.0.8)
Requirement already satisfied: rich in ./anaconda3/lib/python3.8/site-packages/rich-10.1.0-py3.8.egg (from nbterm) (10.1.0)
Requirement already satisfied: kernel-driver in ./anaconda3/lib/python3.8/site-packages/kernel_driver-0.0.5-py3.8.egg (from nbterm) (0.0.5)
Requirement already satisfied: pygments in ./anaconda3/lib/python3.8/site-packages (from nbterm) (2.7.2)
Requirement already satisfied: typer in ./anaconda3/lib/python3.8/site-packages/typer-0.3.2-py3.8.egg (from nbterm) (0.3.2)
Requirement already satisfied: python-dateutil in ./anaconda3/lib/python3.8/site-packages (from kernel-driver->nbterm) (2.8.1)
Requirement already satisfied: pyzmq in ./anaconda3/lib/python3.8/site-packages (from kernel-driver->nbterm) (20.0.0)
Requirement already satisfied: rich in ./anaconda3/lib/python3.8/site-packages/rich-10.1.0-py3.8.egg (from nbterm) (10.1.0)
Requirement already satisfied: wcwidth in ./anaconda3/lib/python3.8/site-packages (from prompt-toolkit>=3->nbterm) (0.2.5)
Requirement already satisfied: six>=1.5 in ./anaconda3/lib/python3.8/site-packages (from python-dateutil->kernel-driver->nbterm) (1.15.0)
Requirement already satisfied: colorama<0.5.0,>=0.4.0 in ./anaconda3/lib/python3.8/site-packages (from rich->nbterm) (0.4.4)
Requirement already satisfied: commonmark<0.10.0,>=0.9.0 in ./anaconda3/lib/python3.8/site-packages/commonmark-0.9.1-py3.8.egg (from rich->nbterm) (0.9.1)
Requirement already satisfied: pygments in ./anaconda3/lib/python3.8/site-packages (from nbterm) (2.7.2)
Requirement already satisfied: typing-extensions<4.0.0,>=3.7.4 in ./anaconda3/lib/python3.8/site-packages (from rich->nbterm) (3.7.4.3)
Requirement already satisfied: click<7.2.0,>=7.1.1 in ./anaconda3/lib/python3.8/site-packages (from typer->nbterm) (7.1.2)
Installing collected packages: nbterm
Successfully installed nbterm-0.0.2
(base) [guido@blue Wed Apr 14 11:12:54] ~
——> nbterm
Traceback (most recent call last):
  File "/home/guido/anaconda3/bin/nbterm", line 5, in <module>
    from nbterm.nbterm import cli
  File "/home/guido/anaconda3/lib/python3.8/site-packages/nbterm/nbterm.py", line 3, in <module>
    from .notebook import Notebook
  File "/home/guido/anaconda3/lib/python3.8/site-packages/nbterm/notebook.py", line 6, in <module>
    from prompt_toolkit.layout import ScrollablePane
ImportError: cannot import name 'ScrollablePane' from 'prompt_toolkit.layout' (/home/guido/anaconda3/lib/python3.8/site-packages/prompt_toolkit/layout/__init__.py)

Thanks

**Comment by davidbrochart** [comment]
Ah, I think you need to `pip install prompt_toolkit>=3.0.16`.

**Comment by guidov** [comment]
Yes that worked! 
I've been waiting forever for a tool that lets you view notebooks in the terminal
Thank you!!!

**Comment by davidbrochart** [comment]
You may also want to check out https://github.com/kracekumar/jut.
