### ISSUE TITLE
Improve the performance of nbterm

### ISSUE THREAD

**Issue by dclong** [davidbrochart/nbterm#26]
nbterm runs slowly on even small notebooks. It responses slowly to navigation keys (up key, down key, etc).

**Comment by davidbrochart** [comment]
My experience is that nbterm doesn't scale well with the number of cells in the notebook, in terms of performance. I am not sure how to improve that, see https://github.com/prompt-toolkit/python-prompt-toolkit/issues/1425.

**Comment by davidbrochart** [comment]
I think the best would be to use the `ScrollingContainer` implemented in euporie, see https://github.com/joouha/euporie/issues/6.
