### ISSUE TITLE
Incompatibility with Click 8

### ISSUE THREAD

**Issue by dprada** [davidbrochart/nbterm#45]
nbterm depends on the library 'click' through the library 'typer'. Right now there is a problem with typer calling click.

For those users installing nbterm with conda-forge, downgrade click as suggested in https://github.com/tiangolo/typer/issues/278

**Comment by davidbrochart** [comment]
Thanks for reporting, do you think I should pin `click <=7` in conda-forge?

**Comment by tiangolo** [comment]
I just released Typer `0.4.0`, which is compatible with **both** Click 7 and Click 8. :tada:

**Comment by davidbrochart** [comment]
Awesome, thanks @tiangolo !
