### ISSUE TITLE
sagemath kernel

### ISSUE THREAD

**Issue by dkwo** [davidbrochart/nbterm#57]
This is just a question: does nbterm work with sagemath kernel?
Thanks.

**Comment by davidbrochart** [comment]
I have not tried, but if it's a Jupyter kernel, it should work.

**Comment by dkwo** [comment]
sagemath definitely provides a jupyter kernel, as e.g. it works in jupyter lab.
I'll try to package dependencies for nbterm and test it soon.

**Comment by dkwo** [comment]
It seems it works with sagemath, thanks.
