### ISSUE TITLE
`C-q` should quit regardless of editing mode

### ISSUE THREAD

**Issue by fperez** [davidbrochart/nbterm#7]
It's a bit weird and confusing that `C-q` doesn't quit when in "cell mode", I think that should be a globally active keybinding (potentially with a save-on-exit-if-file-dirty check as usual, once file dirty status detection/info is implemented).

**Comment by davidbrochart** [comment]
Done in https://github.com/davidbrochart/nbterm/commit/922486862cd2ad375a9b4cd9d9d3d1184c571336.
