### ISSUE TITLE
Reconcile terminology with JupyterLab regarding modes

### ISSUE THREAD

**Issue by fperez** [davidbrochart/nbterm#8]
In both [JuptyerLab](https://jupyterlab.readthedocs.io/en/stable/user/notebook.html?highlight=mode#notebooks) and [Classic](https://nbviewer.jupyter.org/github/jupyter/notebook/blob/master/docs/source/examples/Notebook/Notebook%20Basics.ipynb#Modal-editor) we've always referred to the two modes as "command" and "edit" mode. Currently in nbterm these are called respectively "notebook" and "cell" mode. I suggest adopting the existing terminology, that has been in use for almost a decade, to avoid user confusion (I definitely had to re-read the README more than once to remind myself...)

**Comment by davidbrochart** [comment]
Done in https://github.com/davidbrochart/nbterm/commit/922486862cd2ad375a9b4cd9d9d3d1184c571336.
